{% set name = "nxviz" %}
{% set version = "0.7.2" %}
{% set sha256 = "c924355d03a4cf53839c1db8c58d9561ec224b1b799b91abd224f0e6aee5f9b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - matplotlib-base
    - networkx
    - numpy
    - palettable
    - pandas

test:
  imports:
    - nxviz
    - nxviz.plots
    - nxviz.geometry
    - nxviz.utils

about:
  home: http://github.com/ericmjl/nxviz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Rational network visualizations in Python

  dev_url: https://github.com/ericmjl/nxviz

extra:
  recipe-maintainers:
    - ericmjl
